### ISSUE TITLE
Apparent scoping problem?

### ISSUE THREAD

**Issue by MrJoy** [Shopify/bootsnap#89]
Short form:  There appears to be attempts to call `without_bootsnap_cache` in a context where the resolution chain doesn't include anything on which the method is attached.

Specifically, lines 50, and 58 of `lib/bootsnap/load_path_cache/core_ext/active_support.rb` read:

```
without_bootsnap_cache { super }
```

After upgrading Bootsnap from 1.1.3 to 1.1.4, drawing routes for ActiveAdmin 1.1.0 dies with this error:

```
/Users/jon/.rbenv/versions/2.4.1/gemsets/lightningai.com/gems/bootsnap-1.1.4/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `rescue in depend_on': undefined method `without_bootsnap_cache' for ActiveSupport::Dependencies:Module (NoMethodError)
```

The problem goes away if I remove `ActiveAdmin.routes(self)` from `routes.rb` -- or downgrade to Bootsnap 1.1.3 -- but obviously that's less than ideal.  I presume it means ActiveAdmin is trying to blindly require some things that don't actually exist, but it seems to be tickling some sort of scoping/lifecycle bug in Bootsnap itself.

The problem is fixed if I patch bootsnap (either by editing the relevant file or via monkey-patch) so those lines read like so:

```
Bootsnap::LoadPathCache::CoreExt::ActiveSupport.without_bootsnap_cache { super }
```

If I put those patches in place everything works.  If I also patch `depend_on`'s `rescue` clause to dump info about captured `LoadError`s I get these warnings on load:

```
#<LoadError: No such file to load -- inherited_resources/base_helper.rb>
#<LoadError: No such file to load -- active_admin/base_helper.rb>
#<LoadError: No such file to load -- active_admin/resource_helper.rb>
#<LoadError: No such file to load -- admin/administrators_helper.rb>
#<LoadError: No such file to load -- active_admin/page_helper.rb>
#<LoadError: No such file to load -- admin/dashboard_helper.rb>
#<LoadError: No such file to load -- admin/users_helper.rb>
#<LoadError: No such file to load -- admin/comments_helper.rb>
```

I'm trying to isolate this to a smaller repro-case, but I'm hoping this is enough info to be helpful.

**Comment by MrJoy** [comment]
Here's a simple repro case.  Set the env var `PATCH_BOOTSNAP=1` to employ my workaround.

[testcase.tar.gz](https://github.com/Shopify/bootsnap/files/1361361/testcase.tar.gz)

**Comment by burke** [comment]
This was an issue with 1.1.4, which has now been yanked. I'm going to fix it and release 1.1.5 tomorrow. Sorry about that!

**Comment by MrJoy** [comment]
Gotcha.  Thanks!

**Comment by burke** [comment]
1.1.5 is released, should fix this issue. Please reopen if not.
